export {default as AllProducts} from './All_Products'
export {default as AddProduct} from './Add_Product'
export {default as Dashboard} from './Dashboard'
export {default as Users} from './Users'
export {default as Edit} from './EditProduct'
export {default as Categories} from './Categories'
export {default as OrderLists} from './orderList'
export {default as OrderDetails} from './orderDetails'