export {default as Admin} from './admin'
export {default as Cart} from './cart'
export {default as Contact} from './contact'
export {default as Home} from './home'
export {default as OrderHistory} from './orderHistory'
export {default as Login} from './authention/login'
export {default as Register} from './authention/register'
export {default as Reset} from './authention/reset'
export {default as Shop} from './shop'
export {default as Checkout} from './checkout'
export {default as ProductDetails} from './productDetails'
 